### PR TITLE
feature: kill feed and its assets

### PR DESCRIPTION
**Pull request by zedrix**
Hi, Rock here! I have developed the kill feed component. it shows live kill feed with up to 8 items visible together and a 5 second timeout hiding every item. Let me know if it is ok or you need some changes. 

killfeed example

### CODE REVIEW

**Comment by GeleArthur** [comment]
Closes if merged #18

**Comment by GeleArthur** [comment]
Could you add timer for every kill in the queue so they will automatily be deleted after 4 secondes

**Comment by GeleArthur** [comment]
> Could you add timer for every kill in the queue so they will automatily be deleted after 4 secondes

nvm you did css magic 😎

**Comment by zedrix** [comment]
> > Could you add timer for every kill in the queue so they will automatily be deleted after 4 secondes
> 
> nvm you did css magic 😎

Yup after 4 second it start fading for 1 second and become hidden. The data in the queue array will be deleted when new kills arrive and the size have reached the maxQueueSize

**Review by styledev — COMMENTED** [review]
@GeleArthur Do we need to do anything different with the location of the images in terms of deployment? Since we had to move things last time.

**Comment by GeleArthur** [comment]
> @GeleArthur Do we need to do anything different with the location of the images in terms of deployment? Since we had to move things last time.

As long as its in src/assets its fine. We want to avoid putting it in the public folder because then vite can't encode it

**Review by GeleArthur — CHANGES_REQUESTED** [review]

**Comment by zedrix** [comment]
applied the requested changes ;)

**Review by GeleArthur — APPROVED** [review]

**Pull request merged**
